// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUv5N18xmXpgboY_R1lxKSDI3KmBNIV8',
    appId: '1:512659778824:web:20c63e72325b31b58c10bd',
    messagingSenderId: '512659778824',
    projectId: 'socialmediaapp-36c03',
    authDomain: 'socialmediaapp-36c03.firebaseapp.com',
    storageBucket: 'socialmediaapp-36c03.firebasestorage.app',
    measurementId: 'G-8KJY2TRWRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBeteqB6JBLIR7oJUalhXpyWrgd3eQ6s',
    appId: '1:512659778824:android:57ed32ab9bf544808c10bd',
    messagingSenderId: '512659778824',
    projectId: 'socialmediaapp-36c03',
    storageBucket: 'socialmediaapp-36c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJu62EN-3W_gnyhuO2jn2cy_CshCw0ong',
    appId: '1:512659778824:ios:e780717cf0a9257a8c10bd',
    messagingSenderId: '512659778824',
    projectId: 'socialmediaapp-36c03',
    storageBucket: 'socialmediaapp-36c03.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJu62EN-3W_gnyhuO2jn2cy_CshCw0ong',
    appId: '1:512659778824:ios:e780717cf0a9257a8c10bd',
    messagingSenderId: '512659778824',
    projectId: 'socialmediaapp-36c03',
    storageBucket: 'socialmediaapp-36c03.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAUv5N18xmXpgboY_R1lxKSDI3KmBNIV8',
    appId: '1:512659778824:web:633f8022c44169da8c10bd',
    messagingSenderId: '512659778824',
    projectId: 'socialmediaapp-36c03',
    authDomain: 'socialmediaapp-36c03.firebaseapp.com',
    storageBucket: 'socialmediaapp-36c03.firebasestorage.app',
    measurementId: 'G-PJDBZXG0RQ',
  );
}
